services:
  image: swift-deploy-1-python:latest
  port: 3000
  mode: stable           # "stable" or "canary"
  version: "1.0.0"

nginx:
  image: nginx:latest
  port: 8080
  proxy_timeout: 30s

policy_engine:
  image: openpolicyagent/opa:latest
  port: 8181
  policy_dir: policies
  # Policies are evaluated for each of the domains listed below:
  # The command expects exactly one domain in this list to be evaluated. The domain should be added as a json object in the prompt
  policy_domains:
    - infrastructure
    - canary
    - deployment

network:
  name: swiftdeploy-net
  driver_type: bridge